// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: errorspb.proto

package errorspb

import (
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_UNKNOWN                     ErrorReason = 0 // 内部异常，内部崩溃是 UNKNOWN 500，这里默认值也定义为 UNKNOWN 500，认为这是最佳策略
	ErrorReason_BAD_REQUEST                 ErrorReason = 40000
	ErrorReason_SERVER_DB_ERROR             ErrorReason = 50001
	ErrorReason_SERVER_DB_TRANSACTION_ERROR ErrorReason = 50002
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0:     "UNKNOWN",
		40000: "BAD_REQUEST",
		50001: "SERVER_DB_ERROR",
		50002: "SERVER_DB_TRANSACTION_ERROR",
	}
	ErrorReason_value = map[string]int32{
		"UNKNOWN":                     0,
		"BAD_REQUEST":                 40000,
		"SERVER_DB_ERROR":             50001,
		"SERVER_DB_TRANSACTION_ERROR": 50002,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_errorspb_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_errorspb_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_errorspb_proto_rawDescGZIP(), []int{0}
}

var File_errorspb_proto protoreflect.FileDescriptor

const file_errorspb_proto_rawDesc = "" +
	"\n" +
	"\x0eerrorspb.proto\x12\x11internal.errorspb\x1a\x13errors/errors.proto*\x85\x01\n" +
	"\vErrorReason\x12\x11\n" +
	"\aUNKNOWN\x10\x00\x1a\x04\xa8E\xf4\x03\x12\x17\n" +
	"\vBAD_REQUEST\x10\xc0\xb8\x02\x1a\x04\xa8E\x90\x03\x12\x1b\n" +
	"\x0fSERVER_DB_ERROR\x10ц\x03\x1a\x04\xa8E\xf4\x03\x12'\n" +
	"\x1bSERVER_DB_TRANSACTION_ERROR\x10҆\x03\x1a\x04\xa8E\xf4\x03\x1a\x04\xa0E\xf4\x03B<Z:github.com/orzkratos/gormkratos/internal/errorspb;errorspbb\x06proto3"

var (
	file_errorspb_proto_rawDescOnce sync.Once
	file_errorspb_proto_rawDescData []byte
)

func file_errorspb_proto_rawDescGZIP() []byte {
	file_errorspb_proto_rawDescOnce.Do(func() {
		file_errorspb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errorspb_proto_rawDesc), len(file_errorspb_proto_rawDesc)))
	})
	return file_errorspb_proto_rawDescData
}

var file_errorspb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_errorspb_proto_goTypes = []any{
	(ErrorReason)(0), // 0: internal.errorspb.ErrorReason
}
var file_errorspb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errorspb_proto_init() }
func file_errorspb_proto_init() {
	if File_errorspb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errorspb_proto_rawDesc), len(file_errorspb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errorspb_proto_goTypes,
		DependencyIndexes: file_errorspb_proto_depIdxs,
		EnumInfos:         file_errorspb_proto_enumTypes,
	}.Build()
	File_errorspb_proto = out.File
	file_errorspb_proto_goTypes = nil
	file_errorspb_proto_depIdxs = nil
}
